import { AppDataSource } from "../data-source";
import { Vehicle } from "../../vehicles/entities/vehicle.entity";

async function seedVehicles() {
  try {
    console.log("🌱 Starting vehicles seeding...");

    if (!AppDataSource.isInitialized) {
      await AppDataSource.initialize();
    }

    const vehicleRepository = AppDataSource.getRepository(Vehicle);

    // Check if vehicles already exist
    const existingVehicles = await vehicleRepository.count();

    if (existingVehicles > 0) {
      console.log(`✅ ${existingVehicles} vehicles already exist in database`);
      return;
    }

    // Comprehensive vehicle dataset with all types and varied attributes
    const sampleVehicles = [
      // Cars (15 vehicles)
      {
        type: "Car",
        brand: "Toyota",
        model: "Camry",
        color: "Silver",
        engineSize: "2.5L",
        year: 2023,
        price: 28500.0,
        description: "Experience the perfect blend of reliability and performance with this stunning 2023 Toyota Camry. This silver beauty features a 2.5L engine that delivers both power and efficiency.",
        images: [],
      },
      {
        type: "Car",
        brand: "BMW",
        model: "3 Series",
        color: "White",
        engineSize: "2.0L Turbo",
        year: 2024,
        price: 45200.0,
        description: "Experience luxury and performance with this stunning 2024 BMW 3 Series. This white sedan combines elegant design with a powerful 2.0L Turbo engine.",
        images: [],
      },
      {
        type: "Car",
        brand: "Honda",
        model: "Accord",
        color: "Blue",
        engineSize: "1.5L Turbo",
        year: 2023,
        price: 27900.0,
        description: "Discover reliability and efficiency with this 2023 Honda Accord. Features a fuel-efficient 1.5L Turbo engine and spacious interior perfect for daily commuting.",
        images: [],
      },
      {
        type: "Car",
        brand: "Mercedes-Benz",
        model: "C-Class",
        color: "Black",
        engineSize: "2.0L Turbo",
        year: 2024,
        price: 52400.0,
        description: "Indulge in luxury with this elegant 2024 Mercedes-Benz C-Class. Premium craftsmanship meets advanced technology in this sophisticated sedan.",
        images: [],
      },
      {
        type: "Car",
        brand: "Audi",
        model: "A4",
        color: "Gray",
        engineSize: "2.0L TFSI",
        year: 2023,
        price: 48300.0,
        description: "Experience German engineering at its finest with this 2023 Audi A4. Quattro all-wheel drive and premium interior make every journey exceptional.",
        images: [],
      },
      {
        type: "Car",
        brand: "Nissan",
        model: "Altima",
        color: "Red",
        engineSize: "2.5L",
        year: 2022,
        price: 24500.0,
        description: "Enjoy comfort and value with this 2022 Nissan Altima. Spacious cabin and reliable performance make it perfect for everyday driving.",
        images: [],
      },
      {
        type: "Car",
        brand: "Hyundai",
        model: "Elantra",
        color: "White",
        engineSize: "2.0L",
        year: 2023,
        price: 22400.0,
        description: "Modern design meets efficiency in this 2023 Hyundai Elantra. Great fuel economy and comprehensive warranty coverage included.",
        images: [],
      },
      {
        type: "Car",
        brand: "Volkswagen",
        model: "Passat",
        color: "Navy",
        engineSize: "2.0L TSI",
        year: 2022,
        price: 26800.0,
        description: "European sophistication in this refined 2022 Volkswagen Passat. Comfortable ride and quality interior appointments throughout.",
        images: [],
      },
      {
        type: "Car",
        brand: "Subaru",
        model: "Legacy",
        color: "Green",
        engineSize: "2.5L",
        year: 2023,
        price: 27500.0,
        description: "All-weather confidence with this 2023 Subaru Legacy. Standard all-wheel drive and exceptional safety ratings for peace of mind.",
        images: [],
      },
      {
        type: "Car",
        brand: "Mazda",
        model: "Mazda6",
        color: "Maroon",
        engineSize: "2.5L",
        year: 2022,
        price: 25600.0,
        description: "Driving pleasure redefined in this 2022 Mazda6. Premium interior materials and engaging driving dynamics in an elegant package.",
        images: [],
      },
      {
        type: "Car",
        brand: "Kia",
        model: "K5",
        color: "Yellow",
        engineSize: "1.6L Turbo",
        year: 2023,
        price: 26200.0,
        description: "Bold styling and turbocharged performance in this 2023 Kia K5. Advanced tech features and industry-leading warranty included.",
        images: [],
      },
      {
        type: "Car",
        brand: "Lexus",
        model: "ES",
        color: "Gold",
        engineSize: "2.5L Hybrid",
        year: 2024,
        price: 42300.0,
        description: "Luxury and efficiency combined in this 2024 Lexus ES Hybrid. Whisper-quiet cabin and exceptional fuel economy in a premium package.",
        images: [],
      },
      {
        type: "Car",
        brand: "Acura",
        model: "TLX",
        color: "Purple",
        engineSize: "2.0L Turbo",
        year: 2023,
        price: 39800.0,
        description: "Performance luxury in this 2023 Acura TLX. Super Handling All-Wheel Drive and precision crafted interior for the driving enthusiast.",
        images: [],
      },
      {
        type: "Car",
        brand: "Infiniti",
        model: "Q50",
        color: "Brown",
        engineSize: "3.0L Twin Turbo",
        year: 2022,
        price: 41200.0,
        description: "Power and elegance unite in this 2022 Infiniti Q50. Twin-turbo V6 engine delivers exhilarating performance with luxurious comfort.",
        images: [],
      },
      {
        type: "Car",
        brand: "Cadillac",
        model: "CT5",
        color: "Beige",
        engineSize: "2.0L Turbo",
        year: 2023,
        price: 44500.0,
        description: "American luxury redefined in this 2023 Cadillac CT5. Bold design and advanced technology create an unforgettable driving experience.",
        images: [],
      },

      // SUVs (12 vehicles)
      {
        type: "SUV",
        brand: "Honda",
        model: "CR-V",
        color: "Blue",
        engineSize: "1.5L Turbo",
        year: 2024,
        price: 32400.0,
        description: "Discover your next adventure with this exceptional 2024 Honda CR-V. Perfect balance of performance and fuel economy with spacious interior.",
        images: [],
      },
      {
        type: "SUV",
        brand: "Mazda",
        model: "CX-5",
        color: "Gray",
        engineSize: "2.5L",
        year: 2023,
        price: 29200.0,
        description: "Sophisticated design meets practical functionality in this 2023 Mazda CX-5. Premium interior and engaging driving dynamics.",
        images: [],
      },
      {
        type: "SUV",
        brand: "Toyota",
        model: "RAV4",
        color: "Black",
        engineSize: "2.5L",
        year: 2023,
        price: 31800.0,
        description: "Adventure-ready 2023 Toyota RAV4 with standard all-wheel drive. Rugged capability meets everyday practicality and reliability.",
        images: [],
      },
      {
        type: "SUV",
        brand: "Ford",
        model: "Explorer",
        color: "White",
        engineSize: "2.3L EcoBoost",
        year: 2023,
        price: 38600.0,
        description: "Family adventures await in this spacious 2023 Ford Explorer. Three rows of seating and advanced safety features for peace of mind.",
        images: [],
      },
      {
        type: "SUV",
        brand: "Chevrolet",
        model: "Tahoe",
        color: "Silver",
        engineSize: "5.3L V8",
        year: 2022,
        price: 58900.0,
        description: "Full-size capability in this commanding 2022 Chevrolet Tahoe. Powerful V8 engine and luxurious interior for large families.",
        images: [],
      },
      {
        type: "SUV",
        brand: "BMW",
        model: "X3",
        color: "Red",
        engineSize: "2.0L TwinPower",
        year: 2024,
        price: 49300.0,
        description: "Luxury meets utility in this 2024 BMW X3. Premium materials and dynamic performance in a versatile SUV package.",
        images: [],
      },
      {
        type: "SUV",
        brand: "Mercedes-Benz",
        model: "GLE",
        color: "Navy",
        engineSize: "2.0L Turbo",
        year: 2023,
        price: 62400.0,
        description: "Sophisticated luxury in this 2023 Mercedes-Benz GLE. Advanced technology and refined comfort in an elegant SUV.",
        images: [],
      },
      {
        type: "SUV",
        brand: "Audi",
        model: "Q5",
        color: "Green",
        engineSize: "2.0L TFSI",
        year: 2023,
        price: 48700.0,
        description: "German precision engineering in this 2023 Audi Q5. Quattro all-wheel drive and premium interior create the perfect luxury SUV.",
        images: [],
      },
      {
        type: "SUV",
        brand: "Volvo",
        model: "XC90",
        color: "Orange",
        engineSize: "2.0L Supercharged",
        year: 2022,
        price: 56800.0,
        description: "Scandinavian luxury and safety in this 2022 Volvo XC90. Seven-seat capability with world-class safety technology.",
        images: [],
      },
      {
        type: "SUV",
        brand: "Jeep",
        model: "Grand Cherokee",
        color: "Maroon",
        engineSize: "3.6L V6",
        year: 2023,
        price: 42100.0,
        description: "Legendary capability in this 2023 Jeep Grand Cherokee. Premium interior and advanced 4x4 systems for any terrain.",
        images: [],
      },
      {
        type: "SUV",
        brand: "Acura",
        model: "MDX",
        color: "Gold",
        engineSize: "3.5L V6",
        year: 2022,
        price: 49600.0,
        description: "Three-row luxury in this 2022 Acura MDX. Super Handling All-Wheel Drive and premium amenities for the discerning family.",
        images: [],
      },
      {
        type: "SUV",
        brand: "Infiniti",
        model: "QX60",
        color: "Pink",
        engineSize: "3.5L V6",
        year: 2023,
        price: 47400.0,
        description: "Comfort and versatility in this 2023 Infiniti QX60. Spacious three-row seating with luxury appointments throughout.",
        images: [],
      },

      // Trucks (8 vehicles)
      {
        type: "Truck",
        brand: "Ford",
        model: "F-150",
        color: "Red",
        engineSize: "3.5L V6",
        year: 2023,
        price: 42650.0,
        description: "America's best-selling truck, the 2023 Ford F-150. Powerful EcoBoost engine and advanced towing capabilities for work and play.",
        images: [],
      },
      {
        type: "Truck",
        brand: "Chevrolet",
        model: "Silverado 1500",
        color: "Black",
        engineSize: "5.3L V8",
        year: 2023,
        price: 44200.0,
        description: "Dependable power in this 2023 Chevrolet Silverado 1500. Strong V8 engine and durable construction for demanding tasks.",
        images: [],
      },
      {
        type: "Truck",
        brand: "Ram",
        model: "1500",
        color: "White",
        engineSize: "5.7L HEMI V8",
        year: 2022,
        price: 43800.0,
        description: "HEMI power and premium comfort in this 2022 Ram 1500. Best-in-class ride quality with impressive towing capacity.",
        images: [],
      },
      {
        type: "Truck",
        brand: "GMC",
        model: "Sierra 1500",
        color: "Silver",
        engineSize: "6.2L V8",
        year: 2023,
        price: 48500.0,
        description: "Professional grade capability in this 2023 GMC Sierra 1500. Premium interior and powerful V8 performance.",
        images: [],
      },
      {
        type: "Truck",
        brand: "Toyota",
        model: "Tacoma",
        color: "Gray",
        engineSize: "3.5L V6",
        year: 2023,
        price: 35400.0,
        description: "Reliable mid-size performance in this 2023 Toyota Tacoma. Off-road capability with everyday practicality and durability.",
        images: [],
      },
      {
        type: "Truck",
        brand: "Nissan",
        model: "Titan",
        color: "Blue",
        engineSize: "5.6L V8",
        year: 2022,
        price: 41300.0,
        description: "Bold styling and V8 power in this 2022 Nissan Titan. Spacious crew cab and impressive towing capabilities.",
        images: [],
      },
      {
        type: "Truck",
        brand: "Ford",
        model: "Ranger",
        color: "Green",
        engineSize: "2.3L EcoBoost",
        year: 2023,
        price: 32800.0,
        description: "Mid-size versatility in this 2023 Ford Ranger. EcoBoost efficiency with serious off-road capability and modern technology.",
        images: [],
      },
      {
        type: "Truck",
        brand: "Chevrolet",
        model: "Colorado",
        color: "Orange",
        engineSize: "3.6L V6",
        year: 2022,
        price: 33600.0,
        description: "Right-size capability in this 2022 Chevrolet Colorado. Efficient V6 engine with truck toughness in a manageable size.",
        images: [],
      },

      // Motorcycles (5 vehicles)
      {
        type: "Motorcycle",
        brand: "Yamaha",
        model: "MT-07",
        color: "Black",
        engineSize: "689cc",
        year: 2023,
        price: 7699.0,
        description: "Pure excitement in this 2023 Yamaha MT-07. Lightweight chassis and punchy twin-cylinder engine deliver thrilling performance.",
        images: [],
      },
      {
        type: "Motorcycle",
        brand: "Honda",
        model: "CBR600RR",
        color: "Red",
        engineSize: "599cc",
        year: 2023,
        price: 12199.0,
        description: "Track-inspired performance in this 2023 Honda CBR600RR. Refined supersport engineering for the ultimate riding experience.",
        images: [],
      },
      {
        type: "Motorcycle",
        brand: "Kawasaki",
        model: "Ninja 650",
        color: "Green",
        engineSize: "649cc",
        year: 2022,
        price: 7999.0,
        description: "Perfect balance of performance and comfort in this 2022 Kawasaki Ninja 650. Versatile sport touring capability.",
        images: [],
      },
      {
        type: "Motorcycle",
        brand: "Suzuki",
        model: "GSX-R750",
        color: "Blue",
        engineSize: "750cc",
        year: 2022,
        price: 13799.0,
        description: "Legendary supersport performance in this 2022 Suzuki GSX-R750. Race-bred technology for street and track.",
        images: [],
      },
      {
        type: "Motorcycle",
        brand: "Ducati",
        model: "Monster 821",
        color: "Yellow",
        engineSize: "821cc",
        year: 2021,
        price: 11995.0,
        description: "Italian passion and performance in this 2021 Ducati Monster 821. Distinctive styling with exhilarating L-twin engine.",
        images: [],
      },

      // Bikes (5 vehicles)
      {
        type: "Bike",
        brand: "Harley-Davidson",
        model: "Street 750",
        color: "Black",
        engineSize: "749cc",
        year: 2022,
        price: 7599.0,
        description: "Urban attitude in this 2022 Harley-Davidson Street 750. Liquid-cooled Revolution X engine and dark custom styling.",
        images: [],
      },
      {
        type: "Bike",
        brand: "Indian",
        model: "Scout",
        color: "Silver",
        engineSize: "1133cc",
        year: 2023,
        price: 12999.0,
        description: "American craftsmanship in this 2023 Indian Scout. Smooth liquid-cooled V-twin and timeless cruiser styling.",
        images: [],
      },
      {
        type: "Bike",
        brand: "BMW",
        model: "R1250GS",
        color: "White",
        engineSize: "1254cc",
        year: 2023,
        price: 18995.0,
        description: "Adventure touring excellence in this 2023 BMW R1250GS. ShiftCam technology and legendary off-road capability.",
        images: [],
      },
      {
        type: "Bike",
        brand: "Triumph",
        model: "Bonneville T120",
        color: "Brown",
        engineSize: "1200cc",
        year: 2022,
        price: 12900.0,
        description: "Classic British style in this 2022 Triumph Bonneville T120. Modern performance with timeless vintage appeal.",
        images: [],
      },
      {
        type: "Bike",
        brand: "KTM",
        model: "390 Duke",
        color: "Orange",
        engineSize: "373cc",
        year: 2023,
        price: 5799.0,
        description: "Ready to Race attitude in this 2023 KTM 390 Duke. Lightweight chassis and spirited single-cylinder performance.",
        images: [],
      },

      // Vans (3 vehicles)
      {
        type: "Van",
        brand: "Mercedes-Benz",
        model: "Sprinter",
        color: "White",
        engineSize: "2.0L Turbo Diesel",
        year: 2023,
        price: 52500.0,
        description: "Commercial excellence in this 2023 Mercedes-Benz Sprinter. Reliable turbo diesel engine and customizable cargo space.",
        images: [],
      },
      {
        type: "Van",
        brand: "Ford",
        model: "Transit",
        color: "Gray",
        engineSize: "3.5L V6",
        year: 2022,
        price: 47800.0,
        description: "Versatile capability in this 2022 Ford Transit. Powerful V6 engine and flexible interior configurations for any business need.",
        images: [],
      },
      {
        type: "Van",
        brand: "Chevrolet",
        model: "Express",
        color: "Blue",
        engineSize: "6.0L V8",
        year: 2022,
        price: 45200.0,
        description: "Heavy-duty performance in this 2022 Chevrolet Express. Robust V8 engine and durable construction for demanding commercial use.",
        images: [],
      },

      // Electric Vehicles (2 vehicles)
      {
        type: "Electric Vehicle",
        brand: "Tesla",
        model: "Model 3",
        color: "Black",
        engineSize: "Electric",
        year: 2024,
        price: 47240.0,
        description: "Future of transportation in this 2024 Tesla Model 3. Zero emissions driving with cutting-edge autopilot technology.",
        images: [],
      },
      {
        type: "Electric Vehicle",
        brand: "Tesla",
        model: "Model Y",
        color: "White",
        engineSize: "Electric",
        year: 2023,
        price: 52690.0,
        description: "Electric SUV innovation in this 2023 Tesla Model Y. Spacious interior with incredible performance and advanced safety features.",
        images: [],
      },
    ];

    // Create and save vehicles
    const vehicles = vehicleRepository.create(sampleVehicles);
    await vehicleRepository.save(vehicles);

    console.log(`✅ Successfully seeded ${vehicles.length} sample vehicles`);
    console.log(
      "   Vehicle types:",
      [...new Set(vehicles.map((v) => v.type))].join(", "),
    );
    console.log(
      "   Price range: $",
      Math.min(...vehicles.map((v) => Number(v.price))),
      "- $",
      Math.max(...vehicles.map((v) => Number(v.price))),
    );
  } catch (error) {
    console.error("❌ Error seeding vehicles:", error);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  seedVehicles()
    .then(() => {
      console.log("🎉 Vehicles seeding completed");
      process.exit(0);
    })
    .catch((error) => {
      console.error("❌ Vehicles seeding failed:", error);
      process.exit(1);
    });
}

export { seedVehicles };
